<?php
require_once __DIR__.'/bootstrap.php'; require_login();
$page=$_GET['page']??'dashboard';
$categories=$pdo->query('SELECT * FROM kategori ORDER BY nama')->fetchAll(PDO::FETCH_ASSOC);
$locations=$pdo->query('SELECT * FROM lokasi ORDER BY gedung,ruang,rak')->fetchAll(PDO::FETCH_ASSOC);
function options($rows,$selected,$label){foreach($rows as $r)echo '<option value="'.e($r['id']).'" '.($selected==$r['id']?'selected':'').'>'.e($label($r)).'</option>';}
// Semua perubahan database dilakukan di sini agar route tetap ringkas.
if(is_post()){
 verify_csrf(); $action=$_POST['action']??'';
 if(in_array($action,['save_barang','delete_barang','save_kategori','delete_kategori','save_lokasi','delete_lokasi'])) admin_only();
 try {
  if($action==='save_barang'){ $id=(int)($_POST['id']??0);$nama=trim($_POST['nama']);$stok=(int)$_POST['stok'];if(!$nama||$stok<0)throw new Exception('Nama barang dan stok valid wajib diisi.');if($id){$s=$pdo->prepare('SELECT kode FROM barang WHERE id=?');$s->execute([$id]);$kode=$s->fetchColumn();if(!$kode)throw new Exception('Barang tidak ditemukan.');}else{$next=(int)$pdo->query("SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='barang'")->fetchColumn();$kode='BRG-'.str_pad((string)$next,6,'0',STR_PAD_LEFT);}$data=[$kode,$nama,$_POST['kategori_id']?:null,$stok,trim($_POST['satuan']),$_POST['lokasi_id']?:null,$_POST['kondisi'],$_POST['tanggal_masuk']?:null,trim($_POST['deskripsi'])?:null];if($id){$data[]=$id;$pdo->prepare('UPDATE barang SET kode=?,nama=?,kategori_id=?,stok=?,satuan=?,lokasi_id=?,kondisi=?,tanggal_masuk=?,deskripsi=? WHERE id=?')->execute($data);flash('success','Barang diperbarui.');}else{$pdo->prepare('INSERT INTO barang(kode,nama,kategori_id,stok,satuan,lokasi_id,kondisi,tanggal_masuk,deskripsi) VALUES(?,?,?,?,?,?,?,?,?)')->execute($data);flash('success','Barang '.$kode.' dan QR Code berhasil dibuat.');}header('Location: '.url('index.php?page=barang'));exit;
  }
  if($action==='delete_barang'){$pdo->prepare('UPDATE barang SET aktif=0 WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Barang dinonaktifkan.');header('Location: '.url('index.php?page=barang'));exit;}
  if($action==='save_kategori'){$n=trim($_POST['nama']);if(!$n)throw new Exception('Nama kategori wajib diisi.');$pdo->prepare('INSERT INTO kategori(nama,keterangan) VALUES(?,?)')->execute([$n,trim($_POST['keterangan'])]);flash('success','Kategori ditambahkan.');header('Location: '.url('index.php?page=kategori'));exit;}
  if($action==='delete_kategori'){$pdo->prepare('DELETE FROM kategori WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Kategori dihapus.');header('Location: '.url('index.php?page=kategori'));exit;}
  if($action==='save_lokasi'){$g=trim($_POST['gedung']);if(!$g)throw new Exception('Gedung wajib diisi.');$pdo->prepare('INSERT INTO lokasi(gedung,ruang,rak,keterangan) VALUES(?,?,?,?)')->execute([$g,trim($_POST['ruang']),trim($_POST['rak']),trim($_POST['keterangan'])]);flash('success','Lokasi ditambahkan.');header('Location: '.url('index.php?page=lokasi'));exit;}
  if($action==='delete_lokasi'){$pdo->prepare('DELETE FROM lokasi WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Lokasi dihapus.');header('Location: '.url('index.php?page=lokasi'));exit;}
  if($action==='save_transaksi'){admin_only();$id=(int)$_POST['barang_id'];$jumlah=(int)$_POST['jumlah'];$jenis=$_POST['jenis'];if(!$id||$jumlah<1||!in_array($jenis,['masuk','keluar']))throw new Exception('Data transaksi tidak valid.');$pdo->beginTransaction();$s=$pdo->prepare('SELECT stok FROM barang WHERE id=? AND aktif=1 FOR UPDATE');$s->execute([$id]);$b=$s->fetch();if(!$b)throw new Exception('Barang tidak ditemukan.');if($jenis==='keluar'&&$b['stok']<$jumlah)throw new Exception('Stok tidak mencukupi. Stok tersedia: '.$b['stok']);$pdo->prepare('UPDATE barang SET stok=stok+? WHERE id=?')->execute([$jenis==='masuk'?$jumlah:-$jumlah,$id]);$pdo->prepare('INSERT INTO transaksi(barang_id,jenis,jumlah,tanggal,keterangan,user_id) VALUES(?,?,?,?,?,?)')->execute([$id,$jenis,$jumlah,$_POST['tanggal'],trim($_POST['keterangan']),$_SESSION['user']['id']]);$pdo->commit();flash('success','Transaksi berhasil. Stok telah diperbarui.');header('Location: '.url('index.php?page=riwayat'));exit;
  }
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('danger',$e->getMessage());header('Location: '.url('index.php?page='.$page));exit;}
}
require __DIR__.'/partials/header.php';
if($page==='dashboard'){
 if($_SESSION['user']['role']==='admin') echo '<div class="d-flex justify-content-end mb-3"><a class="btn btn-outline-primary" href="'.url('members.php').'">👥 Kelola Member & Admin</a></div>';
 $stats=['Total barang'=>$pdo->query('SELECT COUNT(*) FROM barang WHERE aktif=1')->fetchColumn(),'Total stok'=>$pdo->query('SELECT COALESCE(SUM(stok),0) FROM barang WHERE aktif=1')->fetchColumn(),'Barang masuk'=>$pdo->query("SELECT COALESCE(SUM(jumlah),0) FROM transaksi WHERE jenis='masuk'")->fetchColumn(),'Barang keluar'=>$pdo->query("SELECT COALESCE(SUM(jumlah),0) FROM transaksi WHERE jenis='keluar'")->fetchColumn(),'Kategori'=>$pdo->query('SELECT COUNT(*) FROM kategori')->fetchColumn()];
 echo '<div class="row g-3 mb-4">';foreach($stats as $k=>$v)echo '<div class="col-6 col-lg"><div class="card h-100"><div class="card-body d-flex align-items-center gap-3"><span class="stat-icon">▣</span><div><small class="text-secondary">'.e($k).'</small><h3 class="mb-0">'.e($v).'</h3></div></div></div></div>';echo '</div>';
 $latest=$pdo->query('SELECT b.*,k.nama kategori,l.gedung,l.ruang,l.rak FROM barang b LEFT JOIN kategori k ON k.id=b.kategori_id LEFT JOIN lokasi l ON l.id=b.lokasi_id WHERE b.aktif=1 ORDER BY b.created_at DESC LIMIT 5')->fetchAll(PDO::FETCH_ASSOC);$act=$pdo->query('SELECT t.*,b.kode,b.nama,u.nama user FROM transaksi t JOIN barang b ON b.id=t.barang_id JOIN users u ON u.id=t.user_id ORDER BY t.created_at DESC LIMIT 6')->fetchAll(PDO::FETCH_ASSOC); ?>
 <div class="row g-4"><div class="col-lg-7"><div class="card"><div class="card-body"><h5>Barang terbaru</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Kode</th><th>Barang</th><th>Stok</th><th>Lokasi</th></tr></thead><tbody><?php foreach($latest as $b):?><tr><td><?=e($b['kode'])?></td><td><?=e($b['nama'])?><br><small class="text-secondary"><?=e($b['kategori']??'-')?></small></td><td><span class="badge text-bg-primary"><?=e($b['stok'].' '.$b['satuan'])?></span></td><td><?=e(location_name($b))?></td></tr><?php endforeach?></tbody></table></div></div></div></div><div class="col-lg-5"><div class="card"><div class="card-body"><h5>Aktivitas storage</h5><?php foreach($act as $a):?><div class="border-bottom py-2"><b><?=e($a['nama'])?></b> <span class="badge text-bg-<?= $a['jenis']==='masuk'?'success':'warning'?>"><?=e($a['jenis'])?></span><br><small class="text-secondary"><?=e($a['jumlah'].' unit oleh '.$a['user'].' · '.$a['tanggal'])?></small></div><?php endforeach?></div></div></div></div>
<?php }
elseif($page==='barang'){
 $q=trim($_GET['q']??'');$cat=$_GET['kategori']??'';$loc=$_GET['lokasi']??'';$where=['b.aktif=1'];$par=[];if($q){$where[]='(b.kode LIKE ? OR b.nama LIKE ?)';$par[]="%$q%";$par[]="%$q%";}if($cat){$where[]='b.kategori_id=?';$par[]=$cat;}if($loc){$where[]='b.lokasi_id=?';$par[]=$loc;}$s=$pdo->prepare('SELECT b.*,k.nama kategori,l.gedung,l.ruang,l.rak FROM barang b LEFT JOIN kategori k ON k.id=b.kategori_id LEFT JOIN lokasi l ON l.id=b.lokasi_id WHERE '.implode(' AND ',$where).' ORDER BY b.created_at DESC');$s->execute($par);$items=$s->fetchAll(PDO::FETCH_ASSOC);$edit=null;if(!empty($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM barang WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch(PDO::FETCH_ASSOC);} ?>
 <div class="d-flex flex-wrap gap-2 justify-content-between mb-3"><form class="d-flex flex-wrap gap-2"><input type="hidden" name="page" value="barang"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Cari kode atau nama"><select class="form-select" name="kategori"><option value="">Semua kategori</option><?php options($categories,$cat,fn($x)=>$x['nama'])?></select><select class="form-select" name="lokasi"><option value="">Semua lokasi</option><?php options($locations,$loc,fn($x)=>location_name($x))?></select><button class="btn btn-outline-primary">Filter</button></form><?php if($_SESSION['user']['role']==='admin'):?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#barangModal">+ Tambah Barang</button><?php endif?></div>
 <div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Kode</th><th>Nama</th><th>Kategori</th><th>Stok</th><th>QR Code</th><th>Lokasi</th><th></th></tr></thead><tbody><?php foreach($items as $b):?><tr><td><b><?=e($b['kode'])?></b></td><td><?=e($b['nama'])?></td><td><?=e($b['kategori']??'-')?></td><td><?=e($b['stok'].' '.$b['satuan'])?></td><td><a target="_blank" href="<?=e(qr_image_url($b['kode']))?>" title="Buka QR Code"><img class="table-qr" src="<?=e(qr_image_url($b['kode'],70))?>" alt="QR <?=e($b['kode'])?>"></a></td><td><?=e(location_name($b))?></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="<?=url('detail.php?kode='.urlencode($b['kode']))?>">Detail</a><?php if($_SESSION['user']['role']==='admin'):?><a class="btn btn-sm btn-outline-secondary" href="<?=url('index.php?page=barang&edit='.$b['id'])?>">Edit</a><form class="d-inline" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_barang"><input type="hidden" name="id" value="<?=e($b['id'])?>"><button data-confirm="Nonaktifkan barang ini?" class="btn btn-sm btn-outline-danger">Hapus</button></form><?php endif?></td></tr><?php endforeach?></tbody></table></div></div>
 <?php if($_SESSION['user']['role']==='admin'):?><div class="modal fade" id="barangModal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="post"><div class="modal-header"><h5><?= $edit?'Edit':'Tambah'?> Barang</h5><a class="btn-close" href="<?=url('index.php?page=barang')?>"></a></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_barang"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><div class="row g-3"><div class="col-md-4"><label class="form-label">Kode *</label><input class="form-control" name="kode" required value="<?=e($edit['kode']??'')?>"></div><div class="col-md-8"><label class="form-label">Nama *</label><input class="form-control" name="nama" required value="<?=e($edit['nama']??'')?>"></div><div class="col-md-6"><label class="form-label">Kategori</label><select class="form-select" name="kategori_id"><option value="">- Pilih -</option><?php options($categories,$edit['kategori_id']??'',fn($x)=>$x['nama'])?></select></div><div class="col-md-3"><label class="form-label">Stok *</label><input class="form-control" type="number" min="0" name="stok" required value="<?=e($edit['stok']??0)?>"></div><div class="col-md-3"><label class="form-label">Satuan</label><input class="form-control" name="satuan" value="<?=e($edit['satuan']??'Unit')?>"></div><div class="col-md-6"><label class="form-label">Lokasi</label><select class="form-select" name="lokasi_id"><option value="">- Pilih -</option><?php options($locations,$edit['lokasi_id']??'',fn($x)=>location_name($x))?></select></div><div class="col-md-3"><label class="form-label">Kondisi</label><select class="form-select" name="kondisi"><?php foreach(['Baik','Rusak Ringan','Rusak Berat'] as $x):?><option <?=($edit['kondisi']??'Baik')===$x?'selected':''?>><?=$x?></option><?php endforeach?></select></div><div class="col-md-3"><label class="form-label">Tgl. masuk</label><input class="form-control" type="date" name="tanggal_masuk" value="<?=e($edit['tanggal_masuk']??date('Y-m-d'))?>"></div><div class="col-12"><label class="form-label">Keterangan</label><textarea class="form-control" name="deskripsi"><?=e($edit['deskripsi']??'')?></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div><?php if($edit):?><script>window.addEventListener('DOMContentLoaded',()=>new bootstrap.Modal('#barangModal').show())</script><?php endif?><?php endif; }
elseif($page==='kategori'){ admin_only(); ?>
<div class="row g-4"><div class="col-lg-4"><div class="card"><div class="card-body"><h5>Tambah kategori</h5><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_kategori"><input class="form-control mb-2" name="nama" placeholder="Nama kategori" required><textarea class="form-control mb-3" name="keterangan" placeholder="Keterangan (opsional)"></textarea><button class="btn btn-primary">Simpan</button></form></div></div></div><div class="col-lg-8"><div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Nama</th><th>Keterangan</th><th></th></tr></thead><tbody><?php foreach($categories as $x):?><tr><td><?=e($x['nama'])?></td><td><?=e($x['keterangan'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_kategori"><input type="hidden" name="id" value="<?=$x['id']?>"><button data-confirm="Hapus kategori ini?" class="btn btn-sm btn-outline-danger">Hapus</button></form></td></tr><?php endforeach?></tbody></table></div></div></div></div>
<?php }
elseif($page==='lokasi'){ admin_only(); ?>
<div class="row g-4"><div class="col-lg-4"><div class="card"><div class="card-body"><h5>Tambah lokasi</h5><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_lokasi"><input class="form-control mb-2" name="gedung" placeholder="Gedung *" required><input class="form-control mb-2" name="ruang" placeholder="Ruang"><input class="form-control mb-2" name="rak" placeholder="Rak"><textarea class="form-control mb-3" name="keterangan" placeholder="Keterangan"></textarea><button class="btn btn-primary">Simpan</button></form></div></div></div><div class="col-lg-8"><div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Lokasi</th><th>Keterangan</th><th></th></tr></thead><tbody><?php foreach($locations as $x):?><tr><td><?=e(location_name($x))?></td><td><?=e($x['keterangan'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_lokasi"><input type="hidden" name="id" value="<?=$x['id']?>"><button data-confirm="Hapus lokasi ini?" class="btn btn-sm btn-outline-danger">Hapus</button></form></td></tr><?php endforeach?></tbody></table></div></div></div></div>
<?php }
elseif($page==='transaksi'){ admin_only(); $items=$pdo->query('SELECT id,kode,nama,stok,satuan FROM barang WHERE aktif=1 ORDER BY nama')->fetchAll(PDO::FETCH_ASSOC); ?>
<div class="row justify-content-center"><div class="col-lg-7"><div class="card"><div class="card-body p-4"><h5 class="mb-3">Catat barang masuk atau keluar</h5><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_transaksi"><div class="mb-3"><label class="form-label">Barang</label><select class="form-select" name="barang_id" required><option value="">Pilih barang</option><?php foreach($items as $b):?><option value="<?=$b['id']?>"><?=e($b['kode'].' — '.$b['nama'].' (stok: '.$b['stok'].' '.$b['satuan'].')')?></option><?php endforeach?></select></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Jenis transaksi</label><select class="form-select" name="jenis"><option value="masuk">Barang Masuk</option><option value="keluar">Barang Keluar</option></select></div><div class="col-md-6"><label class="form-label">Jumlah</label><input class="form-control" type="number" min="1" name="jumlah" required></div><div class="col-md-6"><label class="form-label">Tanggal</label><input class="form-control" type="date" name="tanggal" value="<?=date('Y-m-d')?>" required></div><div class="col-md-6"><label class="form-label">Keterangan</label><input class="form-control" name="keterangan" placeholder="Opsional"></div></div><button class="btn btn-primary mt-4">Simpan Transaksi</button></form></div></div></div></div>
<?php }
elseif($page==='riwayat'){$jenis=$_GET['jenis']??'';$tanggal=$_GET['tanggal']??'';$w=['1=1'];$p=[];if($jenis){$w[]='t.jenis=?';$p[]=$jenis;}if($tanggal){$w[]='t.tanggal=?';$p[]=$tanggal;}$s=$pdo->prepare('SELECT t.*,b.kode,b.nama,u.nama user FROM transaksi t JOIN barang b ON b.id=t.barang_id JOIN users u ON u.id=t.user_id WHERE '.implode(' AND ',$w).' ORDER BY t.tanggal DESC,t.id DESC');$s->execute($p);$rows=$s->fetchAll(PDO::FETCH_ASSOC);?>
<div class="d-flex flex-wrap justify-content-between gap-3 mb-3"><form class="d-flex gap-2 flex-wrap"><input type="hidden" name="page" value="riwayat"><select class="form-select" name="jenis" style="max-width:190px"><option value="">Semua jenis</option><option value="masuk" <?=$jenis==='masuk'?'selected':''?>>Masuk</option><option value="keluar" <?=$jenis==='keluar'?'selected':''?>>Keluar</option></select><input class="form-control" style="max-width:200px" type="date" name="tanggal" value="<?=e($tanggal)?>"><button class="btn btn-outline-primary">Filter</button></form><div class="d-flex gap-2 flex-wrap"><a target="_blank" class="btn btn-outline-dark" href="<?=url('laporan.php?periode=harian&tanggal='.urlencode($tanggal?:date('Y-m-d')))?>">🖨 Laporan Harian</a><form action="<?=url('laporan.php')?>" target="_blank" class="d-flex gap-1"><input type="hidden" name="periode" value="bulanan"><input class="form-control" type="month" name="bulan" value="<?=date('Y-m')?>"><button class="btn btn-primary">🖨 Bulanan</button></form></div></div><div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Tanggal</th><th>Kode</th><th>Barang</th><th>Jenis</th><th>Jumlah</th><th>User</th><th>Keterangan</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['tanggal'])?></td><td><?=e($r['kode'])?></td><td><?=e($r['nama'])?></td><td><span class="badge text-bg-<?=$r['jenis']==='masuk'?'success':'warning'?>"><?=e(ucfirst($r['jenis']))?></span></td><td><?=e($r['jumlah'])?></td><td><?=e($r['user'])?></td><td><?=e($r['keterangan'])?></td></tr><?php endforeach?></tbody></table></div></div>
<?php }
elseif($page==='scan'){ ?>
<div class="card scanner"><div class="card-body text-center p-4"><h5>Scan QR Code Barang</h5><p class="text-secondary">Izinkan akses kamera, lalu arahkan kamera ke QR Code.</p><div id="reader"></div><div id="scanResult" class="mt-3"></div></div></div><script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script><script>function ok(t){document.querySelector('#scanResult').innerHTML='<div class="alert alert-success">QR terbaca. Membuka detail…</div>';try{let u=new URL(t,location.href);location.href=u.href}catch(e){location.href='<?=url('detail.php?kode=')?>'+encodeURIComponent(t)}}new Html5QrcodeScanner('reader',{fps:10,qrbox:{width:230,height:230}},false).render(ok,()=>{});</script>
<?php } else { echo '<div class="alert alert-warning">Halaman tidak ditemukan.</div>'; }
require __DIR__.'/partials/footer.php';
